# Generated by Django 5.2.4 on 2025-07-08 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('plat', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awal', models.CharField(max_length=5)),
                ('tujuan', models.CharField(max_length=5)),
                ('jarak', models.IntegerField()),
                ('waktu_tempuh', models.IntegerField()),
                ('price_per_km', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rute', models.CharField(max_length=5)),
                ('tujuan', models.CharField(max_length=5)),
                ('waktu_asli', models.PositiveIntegerField()),
                ('telat', models.PositiveIntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.driver')),
            ],
        ),
    ]
