# Generated by Django 5.2.4 on 2025-07-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='waktu_asli',
        ),
        migrations.AddField(
            model_name='rute',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
