# Generated by Django 5.2.4 on 2025-07-08 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_transaksi_waktu_asli_rute_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='tujuan',
        ),
        migrations.AddField(
            model_name='transaksi',
            name='waktu_asli',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='rute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.rute'),
        ),
    ]
